### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by EnterTG** [holon-platform/holon-core#137]
I wrote an application that works normally when it is launched in eclipse, while when I export it to a war file and install it on the Tomcat server I get the error "AuthContext is not available as context resource". How can I fix this problem?

**Comment by fparoni** [comment]
Can you provide more details and the code of your application so that we can analyze the project and reproduce the error?

**Comment by EnterTG** [comment]
Code: https://pastebin.com/PYL5cPqF
Full error: https://pastebin.com/JvHnaVRX

**Comment by fparoni** [comment]
The code refers to a Login route and is ok. Is your project correctly running under Eclipse and giving the error only under Tomcat? Do Tomcat succed in deploying the war file, so you get the error only when trying to access the Login route?

**Comment by EnterTG** [comment]
Yes, the error only appears on the Tomcat server. When building the war file, I don't have any errors or warnings. Error appears when navigating to "" so I assumed it was login page but I might be wrong.
