### ISSUE TITLE
DefaultPropertySet  extends ArrayList may be a bug

### ISSUE THREAD

**Issue by loongspirit** [holon-platform/holon-core#141]
For example, to use the Property name as unique property identifier, the Property equals and hashCode strategy can be defined as follows:
```
StringProperty ID1 = StringProperty.create("id").hashCodeProvider(property -> Optional.of(property.getName().hashCode()))
                .equalsHandler((property, other) -> {
                    if (other instanceof Property) {
                        return property.getName().equals(((Property) other).getName());
                    }
                    return false;
                });
        StringProperty ID2 = StringProperty.create("id").hashCodeProvider(property -> Optional.of(property.getName().hashCode()))
                .equalsHandler((property, other) -> {
                    if (other instanceof Property) {
                        return property.getName().equals(((Property) other).getName());
                    }
                    return false;
                });

        PropertySet<?> set1 = PropertySet.builderOf(ID1, ID2).build();
        System.out.println("SET1: " + set1);

        PropertySet<?> set2 = PropertySet.of(ID1, ID2);
        System.out.println("SET2: " + set2);

        PropertySet<?> set3 = PropertySet.builder().add(ID1).add(ID2).build();
        System.out.println("SET3: " + set3);
```

result:

SET1: PropertySet [[PathProperty [name=id, type=class java.lang.String]]]
SET2: PropertySet [[PathProperty [name=id, type=class java.lang.String], PathProperty [name=id, type=class java.lang.String]]]
SET3: PropertySet [[PathProperty [name=id, type=class java.lang.String]]]

when use PropertySet.of(ID1,ID2),it never check the equals and hashCode value. 
#com.holonplatform.core.internal.property.DefaultPropertySet
@SafeVarargs
	public <C extends P> DefaultPropertySet(final C... properties) {
		super();
		if (properties != null) {
			for (C property : properties) {
				add(property);
			}
		}
	}

**Comment by axholo** [comment]
I suppose equals/hashCode check should be performed for each method/builder to ensure consistency.
To be fixed in next release.
